### PR TITLE
Add debug session and messages

### PR DESCRIPTION
**Pull request by wolfv**
@jtpio That's the beginning of the debug session ... let me know what you think.

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @wolfv for this.

For some reasons the `initialize` request still doesn't give any reply when running locally.

Gonna setup some testing so it's easier to try it out.

**Comment by JohanMabille** [comment]
@jtpio you may have to create a folder for the logs of ptvsd. I think ptvsd does not start or crashes if this folder does not exist while it is specified when loading ptvsd in the interpreter. The name of the repo should be "xpython_debug_logs", it should be created in the folder from where you launch jupyter lab. We should improve that in the next xeus python release.

**Comment by jtpio** [comment]
Thanks @JohanMabille for the hint.

I had to create the `xpython_debug_logs` folder next to the notebook being used, instead of where JupyterLab is started (root_dir):

```
tmp
├── Untitled.ipynb
├── xeus.log
└── xpython_debug_logs
    └── ptvsd-27467.log
```

**Comment by jtpio** [comment]
Starting and stopping the debugger:

start-stop

Next step is doing the proper calls to `update_cell` and `setBreakpoints`

**Comment by jtpio** [comment]
The last commit adds the call to `updateCell`. The current start sequence is now:

1. Send `initialize`
2. Send `attach`
3. Retrieve code cell, send `updateCell`
4. Send `setBreakpoints` with `sourcePath` from 3.

Also sending a `disconnect` message when the current cell changes to keep things simple.

init-sequence-cells

**Comment by jtpio** [comment]
Will continue iterating on this in follow-up PRs.

Thanks @wolfv for pushing the initial `DebugSession` interface!

**Comment by wolfv** [comment]
cool!

**Pull request merged**
